include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
  - shield: splitkb_aurora_corne_left
    board: nice_nano
  - shield: splitkb_aurora_corne_right
    board: nice_nano
